
export default {
  themeBackGroundColour: '#F5F7FB',
  primary: '#0033A1',
  text_primary: '#404040',
  version_text: '#BCBCBC',
  background2: '#f7f7f7',
  white: '#ffffff',
  black: '#000000',
  greyColour: '#868686',
  aeps_borderColor: '#C4C4C4',
  aeps_inactive_btn_colour: '#868686',
  ministatement_bg_colour: '#ECECEC',
  statementGreenColour: '#00C337',
  statementRedColour: '#E23B3B',
  shadowBorderColour: '#EFEFEF',
  transactionView: '#F4F4F4',
  transactionAmountGreenColour: '#28A745',
  transactionAmountRedColour: '#E23B3B',
  transactionAmountYellowColour: '#FFC107',
  boxActiveBorderColour: '#CFDCF7',
  dashBorderColour: '#BEBEBE',
  rateAppBackgroundColour: '#DAEBFE',
  letUsKnowColour: '#979797',
  shadowColor: '#686868',
  contactsavebutton: '#d7d7d7',
  primary_red: "#D22B2B",
  green: "green",
}
